#!/usr/bin/env node
/* =============================================================================
   build-css.mjs — regenerate the fix-layer CSS bundles.

   WHY THIS EXISTS

   The Oso Site QA run flagged 17 render-blocking stylesheets in <head>
   (PERF-005), plus 124 requests (PERF-006). Every one of those 17 is one of
   THIS project's own fix-layer files -- a11y-base, target-size, mobile-nav,
   store-rail and so on -- each a separate <link> and each a separate blocking
   request before first paint.

   README says "Pure static, no build step, no dependencies." That is still
   true of the SITE: nothing is compiled to serve it, and the bundles are
   committed. This script is an OPTIONAL developer step, run only when one of
   the source stylesheets changes. Nobody needs it to view, host or deploy the
   bundle.

   WHY SIX BUNDLES AND NOT ONE

   The 47 pages do not share one stylesheet list. Measured across the tree
   there are exactly SIX distinct sequences, because page families add their
   own files -- and, critically, location pages insert location/location.css
   in the MIDDLE of the shared core, between header-fit.css and form-fit.css.

   Concatenating a single shared "core" bundle would therefore MOVE
   location.css from position 6 to position 14 on those pages, silently
   changing the cascade on the six store pages. One bundle per distinct
   sequence keeps every page's order byte-for-byte what it was.

   Pages that share a sequence share a bundle, so the 38 pages on the common
   13-file core all hit the same cached URL.

   WHAT IT REWRITES

   A source at assets/<dir>/<name>.css resolves its relative url() against
   assets/<dir>/. The bundle sits at assets/, one level up, so every relative
   url() is re-based:

       a11y/a11y-panel.css     url('fonts/atkinson-...')  -> a11y/fonts/...
       home/reviews-rating.css url('../in-pages/x.webp')  -> in-pages/x.webp

   Absolute, protocol-relative and data: URLs are left alone. Verified: the
   tree has no @import and no @charset, so neither needs handling. If either
   is ever added, this script will need to hoist it -- it deliberately fails
   loudly rather than emitting a silently broken bundle.

   USAGE
       node build-css.mjs           # rebuild all bundles
       node build-css.mjs --check   # verify bundles match sources, exit 1 if not
   ============================================================================= */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(ROOT, 'assets', 'nf-bundle.manifest.json');
const CHECK = process.argv.includes('--check');

if (!existsSync(MANIFEST)) {
  console.error('FATAL: missing ' + MANIFEST);
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));

/* Re-base one relative url() from the source file's directory to assets/. */
function rebase(css, sourceRel) {
  // sourceRel is like "assets/home/reviews-rating.css"
  const dirRel = posix.dirname(sourceRel.replace(/^assets\//, '')); // "home"
  return css.replace(
    /url\(\s*(['"]?)([^'")]+)\1\s*\)/g,
    (whole, quote, url) => {
      const u = url.trim();
      if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(u)) return whole; // absolute / data: / protocol-relative / fragment
      const resolved = dirRel === '.' ? u : posix.normalize(posix.join(dirRel, u));
      return `url(${quote}${resolved}${quote})`;
    }
  );
}

let failures = 0;

for (const [bundleName, sources] of Object.entries(manifest.bundles)) {
  const parts = [
    '/* ' + '='.repeat(75),
    '   ' + bundleName,
    '',
    '   GENERATED by build-css.mjs — DO NOT EDIT THIS FILE.',
    '   Edit the sources below, then run:  node build-css.mjs',
    '',
    '   Sources, in cascade order:',
    ...sources.map((s, i) => `     ${String(i + 1).padStart(2)}. ${s}`),
    '   ' + '='.repeat(75) + ' */',
    '',
  ];

  for (const rel of sources) {
    const abs = join(ROOT, rel);
    if (!existsSync(abs)) {
      console.error('FATAL: missing source ' + rel + ' (needed by ' + bundleName + ')');
      process.exit(1);
    }
    let css = readFileSync(abs, 'utf8');

    if (/@import\b/.test(css)) {
      console.error('FATAL: ' + rel + ' contains @import. @import is only valid at the');
      console.error('       top of a stylesheet, so it cannot be concatenated safely.');
      console.error('       Inline it, or keep this file as a separate <link>.');
      process.exit(1);
    }
    if (/@charset\b/.test(css)) {
      console.error('FATAL: ' + rel + ' contains @charset, which must be the first');
      console.error('       thing in a stylesheet. Remove it (the bundle is served UTF-8).');
      process.exit(1);
    }

    css = rebase(css, rel.replace(/\\/g, '/'));
    parts.push('/* ' + '-'.repeat(73));
    parts.push('   SOURCE: ' + rel);
    parts.push('   ' + '-'.repeat(73) + ' */');
    parts.push(css.replace(/\s*$/, ''));
    parts.push('');
  }

  const out = parts.join('\n') + '\n';
  const target = join(ROOT, 'assets', bundleName);

  if (CHECK) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== out) {
      console.error('STALE: ' + bundleName + ' does not match its sources');
      failures++;
    } else {
      console.log('ok:    ' + bundleName);
    }
  } else {
    writeFileSync(target, out, 'utf8');
    console.log(
      'wrote: assets/' + bundleName +
      '  (' + sources.length + ' sources, ' + (out.length / 1024).toFixed(1) + 'KB)'
    );
  }
}

if (CHECK && failures) {
  console.error('\n' + failures + ' bundle(s) stale. Run: node build-css.mjs');
  process.exit(1);
}
if (CHECK) console.log('\nAll bundles match their sources.');
